spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022212808?createDatabaseIfNotExist=true'
    username: 2022212808
    password: 2022212808
  #    hikari:
  #      maximum-pool-size: 30
  sql:
    init:
      mode:

  data:
    redis:
      host: 120.46.159.231
      port: 6379
      username: default
      password: 2046
      database: 9
logging:
  level:
    sql: debug
    nefu:
      springboot: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
my:
  key: abc

role:
  manager: 0
  student: 1
  teacher: 2



