spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022212808?createDatabaseIfNotExist=true'
    username: 2022212808
    password: 2022212808
  #    hikari:
  #      maximum-pool-size: 30
  sql:
    init:
      mode:

logging:
  level:
    sql: debug
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
my:
  key: abc

role:
  manager: 0
  student: 1
  teacher: 2



