GET http://localhost:8080/api/teacher/processes
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiIxIiwicm9sZSI6IjEiLCJkZXBJZCI6IjEiLCJleHAiOjE3MzEyNDc1MDMsImlhdCI6MTczMTI0NzUxOSwiZ3JvdXAiOjF9.KxzT5nlGpjyAv0eQNVvKcWqnpgf78SEWMk_cnjeFS1M

###

PATCH http://localhost:8080/api/admin/resetAll
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiIxIiwicm9sZSI6IjEiLCJkZXBJZCI6IjEiLCJleHAiOjE3MzEyNDc1MDMsImlhdCI6MTczMTI0NzUxOSwiZ3JvdXAiOjF9.KxzT5nlGpjyAv0eQNVvKcWqnpgf78SEWMk_cnjeFS1M


###
POST http://localhost:8080/api/graduation/login
Content-Type: application/json

{
  "account":"1",
  "password":"1"
}
###
GET http://localhost:8080/api/graduation/processes
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiIxIiwicm9sZSI6IlIybWQiLCJkZXBJZCI6IjEiLCJleHAiOjE3MzQ0MDcwODgsImlhdCI6MTczMTgxNTA5MiwiZ3JvdXAiOjF9.8hew8FbX8EI9fqnhCx27vtihtPd5xnRUSqILuuvNpJs
